title: "Vulcan"
author: "Halil"
email: "halil@example.com"
description: "Fabricando fit faber"
url: "https://haligultekin.github.io"
baseurl: "/blog"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
future: true
